### ISSUE TITLE
Angular

### ISSUE THREAD

**Issue by gassssty** [caffco/get-video-duration#273]
Hi!! It is possible to run this module in Angular? 

I am trying to do it but I can't. If it is possible, can you write an example 

Thanks!

**Comment by Sumolari** [comment]
`get-audio-duration` uses [`@ffprobe-installer/ffprobe`](https://www.npmjs.com/package/@ffprobe-installer/ffprobe) behind the scenes.

It currently only supports Linux, Windows 7+, and MacOS 10.9+. Browser environments are not supported. You can use it in a server-side-rendering environment, though, but you can't ship the browser a direct usage of this package.
