### ISSUE TITLE
Add a way to take from a video link ?

### ISSUE THREAD

**Issue by RisedSky** [caffco/get-video-duration#5]
Hello, is there a way to take the duration of a youtube video ?

`getDuration('https://www.youtube.com/watch?v=IDVIDEO').then((duration) => {
  console.log(duration);
});`
like that ?

thank you.

**Comment by Sumolari** [comment]
Although it might not seem like that, getting the duration of a 3rd-party hosted video is out of the scope of this module as it requires getting the blob's URL of the video and that is different for each video hosting platform.

However you can mix a module that retrieves such URL (I don't know any) with this:

```javascript
const getBlobURL = require(...); // You'll have to find such a module
const getDuration = require('get-video-duration');

getBlobURL('https://www.youtube.com/watch?v=IDVIDEO')
  .then((url) => getDuration(url))
  .then((duration) => console.log(duration))
```

**Comment by RisedSky** [comment]
Thank you for this answer :)

**Comment by RisedSky** [comment]
Okay so i search and find this code with using ytdl-core module witch give all info of a video (on youtube, (no joke...))

```
YTDL.getInfo(args[1], function (err, info) {
				YouTubeTitle = info.title; //récupere le titre
				YouTubeThumbnail = info.thumbnail_url; //récupere la minia
				YouTubeLink = info.video_url; //récupere le lien de la vidéo

				var date = new Date(null);
				date.setSeconds(info.length_seconds);
				var result = date.toISOString().substr(11, 8); // récupere le temps et le transforme en HH:mm:ss

				YouTubeTime = result; 
			})
```
![image](https://user-images.githubusercontent.com/23197999/35827583-dc788fd8-0abc-11e8-91d0-be4d600eee87.png)
