### ISSUE TITLE
Could not find ffprobe executable

### ISSUE THREAD

**Issue by curtisHubbard** [caffco/get-video-duration#87]
this could be an issue with dependencies not up to date, or within the ffprobe package itself. I am running into an error saying ```Could not find ffprobe executable```. Not sure if this has been addressed yet or I am the first to tell you.

**Comment by Sumolari** [comment]
Might this be related to #26?

**Comment by shaji-Dev** [comment]
Any fix for this yet?

`Could not find ffprobe executable, tried "C:\Users\...\npm\node_modules\firebase-tools\lib\deploy\functions\runtimes\node_modules\@ffprobe-installer\win32-x64\ffprobe.exe" and "C:\Us
ers\...\npm\node_modules\firebase-tools\lib\deploy\functions\runtimes\node\node_modules\@ffprobe-installer\win32-x64\ffprobe.exe"`

**Comment by Sumolari** [comment]
> Any fix for this yet?
> 
> 
> 
> `Could not find ffprobe executable, tried "C:\Users\...\npm\node_modules\firebase-tools\lib\deploy\functions\runtimes\node_modules\@ffprobe-installer\ win32-x64\ffprobe.exe" and "C:\Us
> 
> ers\...\npm\node_modules\firebase-tools\lib\deploy\functions\runtimes\node\node_modules\@ffprobe-installer\win32-x64\ffprobe.exe"`
> 
> 

Is it an Electron app?
Is there anything in `C:\Users\...\npm\node_modules\firebase-tools\lib\deploy\functions\runtimes\node_modules\@ffprobe-installer`?

**Comment by gbourne1** [comment]
The issue, for me at least, is the node-ffprobe-installer package can't find the build for my platform:

SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @ffprobe-installer/win32-ia32@4.1.0: wanted {"os":"win32","arch":"ia32"} (current: {"os":"darwin","arch":"x64"})

Thus, ffprobe isn't installed. Try installing node-ffprobe-installer and see if you get any errors.

**Comment by curtisHubbard** [comment]
I bumped get-video-duration down a version and things have been working file. currently running on ```3.0.2```

**Comment by EliasTouil** [comment]
> I bumped get-video-duration down a version and things have been working file. currently running on `3.0.2`

I'm experiencing the same issue as you, unfortunately, I can't go to 3.0.2 as I'm on apple silicon

**Comment by BillCarterNet** [comment]
I had this issue also, everything worked fine on windows...
But when I ran on an azure ubuntu agent I got the error about not finding the executable.

I also have **@ffmpeg-installer/ffmpeg** and **fluent-mpeg** installed and am ultimately chopping up some cypress videos with **ffmpeg** commands.
I was using **get-video-duration** in this process.

Incidentally I got a similar message when trying to use ffprobe directly to get the video duration (some maybe the problem lies elsewhere):

`var ffmpeg = require('fluent-ffmpeg');

ffmpeg.ffprobe('./input.mp4', function(err, metadata) {
    //console.dir(metadata); // all metadata
    console.log(metadata.format.duration);
});`

Ultimately I got around the problem by using a different module, **node-video-lib** to get video durations and everything is working again (this doesnt use ffmpeg/ffprobe).

I dont know if this helps anybody.

I spent a lot of time trying to resolve it so would love to know what is actually going on here

**Comment by paintoshi** [comment]
@BillCarterNet 
In my case it was all about this library linking to the wrong path. Both for windows and linux.

Just do this: `yarn add @ffprobe-installer/ffprobe`
Run your app and it will say where it tried to find ffprobe.

Then go to `/node_modules/@ffprobe-installer/linux-x64` and copy both ffprobe and package.json over to wherever it wants it from the error message. In my it was `/home/ubuntu/.nvm/versions/node/v17.2.0/node_modules/@ffprobe-installer/linux-x64/`

Which means I first created this directory by `mkdir -p /home/ubuntu/.nvm/versions/node/v17.2.0/node_modules/@ffprobe-installer/linux-x64/`

Then it works!

**Comment by lingdocs** [comment]
Yes, @paintoshi 's method worked for me. In my case I was using this in a [Next.js](https://nextjs.org/) app and so I just added the following line to my Dockerfile, and then it would move the binary (which I also installed separately from @ffprobe-installer) into the place where the next app looks for it.

```docker
RUN mkdir /app/node_modules/next/dist/node_modules
RUN mv /app/node_modules/@ffprobe-installer /app/node_modules/next/dist/node_modules
```

**Comment by hamzaazad** [comment]
Any solution?

**Comment by Sumolari** [comment]
`v4.1.0` has a new, optional, parameter that you can provide to override the path to `ffprobe`. When not provided, `get-video-duration` will take the path from `@ffprobe-installer/ffprobe`.

**Comment by Marwan1998** [comment]
i still have this issue

**Comment by Sumolari** [comment]
@Marwan1998 have you tried the new optional parameter passing the correct path for your environment?

**Comment by Marwan1998** [comment]
> @Marwan1998 have you tried the new optional parameter passing the correct path for your environment?

I didn't even write any code yet, this error appears from only importing the package using the import keyword.
btw I have another project using the same package that works perfectly, but in this project I use the old require to require the package.
it works using only require, not import (I tried several versions of the package), using Node.js.
Any suggestion, please?

**Comment by atumas-bananamilk** [comment]
Failing after deploying to Vercel:
```
Error: Could not find ffprobe executable, tried "/var/task/node_modules/get-video-duration/node_modules/@ffprobe-installer/linux-x64/ffprobe" and "/var/task/node_modules/get-video-duration/node_modules/@ffprobe-installer/ffprobe/node_modules/@ffprobe-installer/linux-x64/ffprobe"
```

`get-video-duration` version: `4.1.0`

**Comment by VioletPhilipN** [comment]
I am still getting: 
```
Error: Could not find ffprobe executable
throw new Error('Could not find ffprobe executable, tried "' + npm3Binary + '" and "' + npm2Binary + '"');
```

I have added the extra ffprobe parameter but still not working. 
Am I doing something wrong? Or how did you guys fix this? I am on an M1 Pro. 
Thank you in advance

@Sumolari

**Comment by hminh2027** [comment]
> @BillCarterNet In my case it was all about this library linking to the wrong path. Both for windows and linux.
> 
> Run your app and it will say where it tried to find ffprobe.
> 
> Install: `yarn add @ffprobe-installer/ffprobe` Then go to `/node_modules/@ffprobe-installer/linux-x64` and copy both ffprobe and package.json over to wherever it wants it from the error message. In my case it was `/home/ubuntu/.nvm/versions/node/v17.2.0/node_modules/@ffprobe-installer/linux-x64/`
> 
> Which means I first created this directory by `mkdir -p /home/ubuntu/.nvm/versions/node/v17.2.0/node_modules/@ffprobe-installer/linux-x64/`
> 
> Then just: `cp /node_modules/@ffprobe-installer/linux-x64/ffprobe /home/ubuntu/.nvm/versions/node/v17.2.0/node_modules/@ffprobe-installer/linux-x64/`
> 
> and `cp /node_modules/@ffprobe-installer/linux-x64/package.json /home/ubuntu/.nvm/versions/node/v17.2.0/node_modules/@ffprobe-installer/linux-x64/`
> 
> Then it works!

This works for me. I moved the `ffprobe` file to the exact path needed by the library (in my case the path folder was: `get-video-duration/node_modules/@ffprobe-installer/darwin-arm64`)

**Comment by vkkis93** [comment]
I had the same problem on my MacBook M1 Pro Sequoia.
There are two possible solutions

1. Use version either `3.1.0` or `4.0.0`
2. In case of version `4.1.0` copy `@ffprobe-installer/darwin-arm64` to `get-video-duration/node_modules/`, so your path should look `mySuperProject/node_modules/get-video-duration/node_modules/@ffprobe-installer/darwin-arm64/ffprobe`
